name: Sabotage
main: com.github.NinjaWolf.Sabotage.Sabotage
load: STARTUP
version: 1.0
description: Custom PvP Arena Plugin
author: NinjaWolf
website: https://github.com/NinjaWolf/Sabotage
commands:
    join:
        aliases: ['st join', 'sabotage join']
        description: Joins the Game.
    leave:
        aliases: ['st leave', 'sabotage leave']
        description: Leaves the Game.
    list:
        aliases: ['st list', 'sabotage list']
        description: Displays List of Online Players.
    sabotage:
        aliases: ['st', 'st help', 'sabotage help', 'help']
        description: Displays Commands for Sabotage.
permissions:
    st.admin:
        description: Gives Admin control over plugin.
        default: op
    st.join:
        description: Allows Player to Join the game.
        default: op
    st.leave:
        description: Allows Player to Leave the game.
        default: op
    st.help:
        description: Allows Player to Display Commands.
        default: op
